
apiVersion: v1
kind: Pod
metadata:
  name: pod-tolerate
  labels:
    tained: "true"
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-tolerate
  labels:
    tained: "true"
spec:
  tolerations:
    - key: "hardware"
      operator: "Equal"
      value: "gpu"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx
