apiVersion: v1
kind: Pod
metadata:
  name: assign-pod-node
spec:
  containers:
    - name: nginx
      image: nginx
  nodeSelector:
    hostname: acctsrv


# kubectl label nodes ip-192-168-18-187.ec2.internal hostname=acctsrv

# if the node is tainted, then we have to add toleratons as well along with nodeselector

# https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/