apiVersion: v1
kind: Pod
metadata: 
  name: pod1
  labels:
    purpose: pod-affinity-anit-affinity
spec:
  containers:
    - name: nginx
      image: nginx
---

apiVersion: v1
kind: Pod
metadata: 
  name: pod2
  labels:
    purpose: pod-affinity-anit-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - pod-affinity-anit-affinity
        topologyKey: topology.kubernetes.io/zone
  containers:
    - name: nginx
      image: nginx

---
apiVersion: v1
kind: Pod
metadata: 
  name: pod3
  labels:
    purpose: pod-anti-affinity
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - pod-affinity-anit-affinity
        topologyKey: topology.kubernetes.io/zone
  containers:
    - name: nginx
      image: nginx